// HOME PAGE PRODUCT LISTING
export const GET_HOME_PAGE_PRODUCTS = 'GET_HOME_PAGE_PRODUCTS';
export const GET_HOME_PAGE_PRODUCTS_SUCCESS = 'GET_HOME_PAGE_PRODUCTS_SUCCESS';
export const GET_HOME_PAGE_PRODUCTS_FAILURE = 'GET_HOME_PAGE_PRODUCTS_FAILURE';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

// LIST ACTION
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_ALL = 'ADD_ALL';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CLEAR_LIST = 'CLEAR_LIST';
